// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ScpmBe.Repositories.Infrastructure;
using System;
using System.Collections.Generic;

namespace ScpmaBe.Repositories.Entities;

public partial class AssignedTask : IEntityBase
{
    public int AssignedTaskId { get; set; }

    public int TaskEachId { get; set; }

    public int StaffId { get; set; }

    public DateOnly ShiftDate { get; set; }

    public TimeOnly ShiftTime { get; set; }

    public string Address { get; set; }

    public string Note { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime UpdatedDate { get; set; }

    public virtual Staff Staff { get; set; }

    public virtual TaskEach TaskEach { get; set; }
}