// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ScpmBe.Repositories.Infrastructure;
using System;
using System.Collections.Generic;

namespace ScpmaBe.Repositories.Entities;

public partial class Contract : IEntityBase
{
    public int ContractId { get; set; }

    public int CarId { get; set; }

    public int ParkingSpaceId { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly EndDate { get; set; }

    public int Status { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime UpdatedDate { get; set; }

    public string Note { get; set; }

    public virtual Car Car { get; set; }

    public virtual ParkingSpace ParkingSpace { get; set; }

    public virtual ICollection<PaymentContract> PaymentContracts { get; set; } = new List<PaymentContract>();
}