// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ScpmBe.Repositories.Infrastructure;
using System;
using System.Collections.Generic;

namespace ScpmaBe.Repositories.Entities;

public partial class Floor : IEntityBase
{
    public int FloorId { get; set; }

    public int AreaId { get; set; }

    public string FloorName { get; set; }

    public int NumberEmptyParkingSpace { get; set; }

    public int NumberUsedParkingSpace { get; set; }

    public int TotalParkingSpace { get; set; }

    public int Status { get; set; }

    public virtual Area Area { get; set; }

    public virtual ICollection<ParkingSpace> ParkingSpaces { get; set; } = new List<ParkingSpace>();
}