// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ScpmBe.Repositories.Infrastructure;
using System;
using System.Collections.Generic;

namespace ScpmaBe.Repositories.Entities;

public partial class ParkingSpace : IEntityBase
{
    public int ParkingSpaceId { get; set; }

    public int FloorId { get; set; }

    public string ParkingSpaceName { get; set; }

    public int Status { get; set; }

    public virtual ICollection<Contract> Contracts { get; set; } = new List<Contract>();

    public virtual ICollection<EntryExitLog> EntryExitLogs { get; set; } = new List<EntryExitLog>();

    public virtual Floor Floor { get; set; }

    public virtual ICollection<ParkingStatusSensor> ParkingStatusSensors { get; set; } = new List<ParkingStatusSensor>();
}