// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ScpmBe.Repositories.Infrastructure;
using System;
using System.Collections.Generic;

namespace ScpmaBe.Repositories.Entities;

public partial class ParkingLot : IEntityBase
{
    public int ParkingLotId { get; set; }

    public int OwnerId { get; set; }

    public decimal PricePerHour { get; set; }

    public decimal PricePerDay { get; set; }

    public decimal PricePerMonth { get; set; }

    public string Address { get; set; }

    public double? Long { get; set; }

    public double? Lat { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime UpdatedDate { get; set; }

    public virtual ICollection<Area> Areas { get; set; } = new List<Area>();

    public virtual Owner Owner { get; set; }

    public virtual ICollection<ParkingLotPriceHistory> ParkingLotPriceHistories { get; set; } = new List<ParkingLotPriceHistory>();
}