// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ScpmBe.Repositories.Infrastructure;
using System;
using System.Collections.Generic;

namespace ScpmaBe.Repositories.Entities;

public partial class ParkingLotPriceHistory : IEntityBase
{
    public int PriceLotPriceHistoryId { get; set; }

    public int ParkingLotId { get; set; }

    public decimal PricePerHour { get; set; }

    public decimal PricePerDay { get; set; }

    public decimal PricePerMonth { get; set; }

    public DateTime EffectiveDate { get; set; }

    public virtual ParkingLot ParkingLot { get; set; }
}