// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ScpmBe.Repositories.Infrastructure;
using System;
using System.Collections.Generic;

namespace ScpmaBe.Repositories.Entities;

public partial class Staff : IEntityBase
{
    public int StaffId { get; set; }

    public int OwnerId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<TaskEach> TaskEachs { get; set; } = new List<TaskEach>();
}